export const CLIENT_LOGOS = [
  { name: 'Cooc', src: '/images/Logos/Cooc.png', width: 2807, height: 787, fit: 'wide', ink: true },
  { name: 'Damu', src: '/images/Logos/Damu.png', width: 2145, height: 409, fit: 'wide', ink: true },
  {
    name: 'Field & Sons',
    src: '/images/Logos/Field and Sons.png',
    width: 505,
    height: 148,
    fit: 'wide',
    ink: false,
  },
  {
    name: 'Mandrake',
    src: '/images/Logos/Mandrake.png',
    width: 2717,
    height: 2095,
    fit: 'mark',
    ink: true,
  },
  { name: 'Palm', src: '/images/Logos/Palm.png', width: 296, height: 106, fit: 'wide', ink: true },
  { name: 'RSM', src: '/images/Logos/RSM.png', width: 1252, height: 567, fit: 'wide', ink: true },
  {
    name: 'Starmentality',
    src: '/images/Logos/Starmentality.avif',
    width: 162,
    height: 186,
    fit: 'mark',
    ink: true,
  },
  { name: 'Tricz', src: '/images/Logos/Tricz.png', width: 1181, height: 444, fit: 'wide', ink: false },
  {
    name: 'Upper Crust',
    src: '/images/Logos/upper-crust.png',
    width: 422,
    height: 182,
    fit: 'wide',
    ink: true,
  },
] as const
