import { blocks, decision, fact } from '@/lib/case-study-blocks'
import type { CaseStudyCard, CaseStudyPage } from '@/lib/sanity/types'

export const SESAHUB_SLUG = 'sesahub'

export const SESAHUB_CARD: CaseStudyCard = {
  _id: 'caseStudy-sesahub',
  title: 'SesaHub',
  slug: SESAHUB_SLUG,
  role: 'Product Designer, Full Stack Developer',
  year: 2025,
  summary:
    'An internal multi-tenant ERP — companies, sites, people, stock and a general ledger in one Laravel and React app, scoped so one company cannot see another.',
  status: 'shipped',
  heroImage: null,
}

export const SESAHUB_STUDY: CaseStudyPage = {
  _id: 'caseStudy-sesahub',
  title: 'SesaHub',
  slug: SESAHUB_SLUG,
  role: 'Product Designer, Full Stack Developer',
  year: 2025,
  summary:
    'An internal multi-tenant ERP — companies, sites, people, stock and a general ledger in one Laravel and React app, scoped so one company cannot see another.',
  status: 'shipped',
  contextFacts: [
    fact('Client', 'Nyande ERP Solutions (internal)'),
    fact('Type', 'Multi-tenant ERP'),
    fact('Stack', 'Laravel 11, React, TypeScript, Inertia.js, Tailwind, PostgreSQL'),
    fact('Team', 'Dominic Nyande, business analyst; Amy Nyande, data analyst'),
  ],
  heroImages: [],
  seoTitle: 'SesaHub — Product Design & Build Case Study | Richard Nyande',
  seoDescription:
    'Internal product, 2024–25. A Laravel and React ERP for multi-company operations: sites, employees, inventory, currency and core financials, deployed on Render.',
  ogImage: null,
  reframing: {
    eyebrow: 'Beyond another imported ERP',
    heading:
      'The work was one login across companies, sites and books — not a Western suite with the extra modules left on.',
    intro:
      'SesaHub is Nyande ERP Solutions, an internal family product. There is no external client. TechCorp Solutions Ltd in the general ledger shot is seeded test data, not a customer.',
    initialProposal: blocks(
      'Buy or rent an existing ERP and live with modules written for a different market, or keep companies, stock, people and books in separate tools.'
    ),
    discovery: blocks(
      'Multi-company isolation had to be the permission model, not a filter on a shared table. Sites needed codes. Employees belonged to sites. Stock was per site. Currency had to convert inside the same app. The older public write-up listed a purchase-order pipeline — request, approval, shipment, receipt — that is not a finished workflow. Core financials were missing from that write-up and are in the running build: chart of accounts, journals, trial balance, fiscal calendar.'
    ),
    productResponse: blocks(
      'Laravel 11 with React, TypeScript and Inertia. Company-scoped RBAC and policies. Services for company, site, employee, customer, supplier, product and currency. Docker on Render with PostgreSQL. I designed and built the screens. Dominic Nyande was the business analyst; Amy Nyande was the data analyst.'
    ),
  },
  productModules: {
    eyebrow: 'Mapping the reality.',
    heading: 'Enterprise records first, then the books that have to match them.',
    intro:
      'Built December 2024 to October 2025. Companies, sites, people, customers, suppliers, parts and currency, then core financials. The purchase-order request-to-receipt path was described on an older page; it is not shipped here. Screens are from the running app on seeded test data. There is no companies-list still yet — that module will not borrow another screen.',
    items: [
      {
        title: 'Multi-company',
        shortLabel: 'Companies',
        teaser:
          'Each company is its own environment. Consultants can hold roles across companies; data does not leak between them.',
        status: 'shipped',
        problem: blocks(
          'A family product for more than one company cannot share a single admin table and hope a dropdown is enough. Permissions, currency and the books have to start from the company, or isolation is theatre.'
        ),
        solution: blocks(
          'A company record with company-scoped RBAC and policies. Creating a company initialises its financial system rather than leaving the ledger as a later bolt-on.'
        ),
        before: [
          'Separate tools per company, or one database everyone can see',
          'Permissions as a UI filter',
        ],
        after: [
          'Company-scoped policies',
          'Cross-company roles for consultants without shared rows',
          'Financials initialised with the company',
        ],
      },
      {
        title: 'Sites',
        shortLabel: 'Sites',
        teaser:
          'Locations under a company, with codes generated by the service instead of typed by hand.',
        status: 'shipped',
        problem: blocks(
          'Stock, people and fulfilment are per site. If a site is only a name on a company, inventory and employees have nothing reliable to join to.'
        ),
        solution: blocks(
          'A sites resource on the company. SiteService issues the code. Employees and part inventory hang off that record.'
        ),
        before: [
          'Location as a note on the company',
          'Hand-assigned site codes',
        ],
        after: [
          'Site list under the company',
          'Auto-generated codes',
          'Employees and inventory join to the site',
        ],
      },
      {
        title: 'Employees',
        shortLabel: 'HR',
        teaser:
          'People belong to a site. IDs are generated. Status and department sit on the same record as the login.',
        status: 'shipped',
        problem: blocks(
          'HR sitting in a spreadsheet next to the ERP means site assignment, access and the employee record drift apart.'
        ),
        solution: blocks(
          'An employees resource with site assignment, generated IDs, department and status, tied into the same user and RBAC model as the rest of the app.'
        ),
        before: [
          'Staff lists off-system',
          'No join from a person to a site',
        ],
        after: [
          'Employee IDs issued by the service',
          'Site assignment on the record',
          'Login and role on the same person',
        ],
      },
      {
        title: 'Customers and suppliers',
        shortLabel: 'Parties',
        teaser:
          'Customer records with addresses and orders, and supplier records, so procurement is not only a name in a cell.',
        status: 'shipped',
        problem: blocks(
          'Inventory and books need counterparties. Without customer and supplier records, orders and purchases have nowhere to attach.'
        ),
        solution: blocks(
          'Customers with addresses and customer orders. Suppliers as their own resource. That is the party layer. It is not a finished purchase-order workflow.'
        ),
        before: [
          'Counterparties in a sheet or in someone’s head',
        ],
        after: [
          'Customer records, addresses and orders',
          'Supplier records',
          'Purchase-order steps still a later module',
        ],
      },
      {
        title: 'Products and inventory',
        shortLabel: 'Stock',
        teaser:
          'Parts and categories, with inventory per site — SKU and barcode on the item, levels on the site.',
        status: 'shipped',
        problem: blocks(
          'A quantity on the company hides which site can fulfil. Categories and identifiers have to survive more than one location.'
        ),
        solution: blocks(
          'Parts, product categories and part inventory. Stock levels live on the site. SKU and barcode sit on the part.'
        ),
        before: [
          'One stock number for the whole company',
          'Categories remembered, not stored',
        ],
        after: [
          'Part records with SKU and barcode',
          'Category taxonomy',
          'Inventory rows per site',
        ],
      },
      {
        title: 'Currency',
        shortLabel: 'FX',
        teaser:
          'Rates in the app, with convert and update-rates endpoints, so a company is not stuck in one currency.',
        status: 'shipped',
        problem: blocks(
          'Multi-company work across Ghana and other markets cannot price and book in a single hard-coded currency.'
        ),
        solution: blocks(
          'A currencies resource plus convert and update-rates. Overrides stay available per company and transaction rather than only as a global default.'
        ),
        before: [
          'One currency assumed for every company',
          'Rates looked up off-system',
        ],
        after: [
          'Currency records in the app',
          'Conversion and rate-update endpoints',
          'Company and transaction overrides',
        ],
      },
      {
        title: 'Core financials',
        shortLabel: 'Ledger',
        teaser:
          'Chart of accounts, general ledger, journal entries, trial balance and fiscal calendar — in the same app as stock and people.',
        status: 'shipped',
        problem: blocks(
          'If the books live in another product, the ERP is a set of lists. Journal entries and a fiscal calendar have to belong to the company that owns the stock.'
        ),
        solution: blocks(
          'Core financials as a first-class route group: accounts, ledger, journals, trial balance, account analysis, fiscal calendar. Double-entry in the same tenant as the enterprise records. The screenshot is the TechCorp test company with zeroed balances.'
        ),
        before: [
          'Books in a separate tool, or not at all',
          'No fiscal period on the company',
        ],
        after: [
          'Chart of accounts and general ledger',
          'Journal entries and trial balance',
          'Fiscal calendar on the same login',
        ],
      },
      {
        title: 'Purchase orders',
        shortLabel: 'POs',
        teaser:
          'Described on an older page as request through receipt. Suppliers and customer orders exist; that pipeline does not.',
        status: 'in-progress',
        problem: blocks(
          'The public write-up listed an end-to-end purchase workflow. Shipping that copy as a finished module would have been a gallery of empty laptop frames.'
        ),
        solution: blocks(
          'Supplier records and customer orders are in the build. The request → approval → purchase → shipment → receipt path is not. It stays marked in progress.'
        ),
        before: [
          'A written PO pipeline with no screen to show',
        ],
        after: [
          'Supplier and order foundations in place',
          'PO workflow not presented as shipped',
        ],
      },
    ],
  },
  deepDives: {
    eyebrow: '04 / Deep dives',
    heading: 'Three problems that were not a dashboard skin',
    intro:
      'The older page talked about African enterprises and empty MacBooks. The work that mattered was company-scoped access, a ledger in the same app, and not publishing a purchase-order story the routes do not support.',
    items: [
      {
        title: 'From a shared table to company-scoped access',
        shortLabel: 'Tenancy',
        problem: blocks(
          'An ERP for more than one company fails the moment a consultant can see another company’s employees or books. A company dropdown on a global query is not isolation.'
        ),
        contribution:
          'I built companies as the tenant. Policies and RBAC are company-scoped. Consultants can hold roles across companies without sharing rows. Creating a company starts its financial system rather than leaving a blank ledger for later.',
        constraints:
          'No external client brief to hide behind — this is an internal product.\nDominic Nyande was the business analyst; Amy Nyande was the data analyst.\nData isolation had to hold for employees, sites, stock and the ledger, not only the company list.',
        decisions: [
          decision(
            'Scope by policy, not by a filter in the UI',
            'CompanyRBACService and policies sit on the records. A missed where clause should not be the only thing keeping tenants apart.'
          ),
          decision(
            'Initialise the books with the company',
            'A company without a chart of accounts is a list. Financial setup runs when the company is created.'
          ),
        ],
        outcome: blocks(
          'Shipped. Companies, sites, people and the ledger share the same tenant rules.'
        ),
      },
      {
        title: 'From lists to a ledger in the same app',
        shortLabel: 'Financials',
        problem: blocks(
          'The first public write-up did not mention core financials. Stock and people without journals still send someone to a spreadsheet or another product for the books.'
        ),
        contribution:
          'I added chart of accounts, general ledger, journal entries, trial balance and a fiscal calendar as a route group next to enterprise. The general ledger screenshot is that module, on seeded TechCorp data, balances at zero.',
        constraints:
          'Double-entry has to belong to the same company as the parts and employees.\nThe screenshot is test data and is labelled as such.\nI will not publish named-client outcomes I do not have.',
        decisions: [
          decision(
            'Ship the books as a module, not an export',
            'Trial balance and journals are screens in the app. They are not a CSV out to someone else’s accounting tool.'
          ),
          decision(
            'Show the test company honestly',
            'TechCorp Solutions Ltd is seed data. Using it as a client logo would have been a lie.'
          ),
        ],
        outcome: blocks(
          'Shipped in the running build. The hero image is this ledger, not a marketing render.'
        ),
      },
      {
        title: 'From a written PO pipeline to what the routes actually do',
        shortLabel: 'Honesty',
        problem: blocks(
          'The older case study listed purchase orders and shipments as if they were done, then showed empty MacBook frames and a registration clip from another stack.'
        ),
        contribution:
          'I kept suppliers and customer orders in the story because they exist. I marked request-to-receipt as in progress. I did not reuse another project’s UI, and I dropped the MemberPress registration block that had landed on that page by mistake.',
        constraints:
          'Empty laptop mockups are not product screenshots.\nMemberPress, Divi and New User Approve were never this stack.\nA live URL is omitted until there is one to print.',
        decisions: [
          decision(
            'Do not ship a gallery of blank laptops',
            'Modules without a still show as image coming soon. Companies and purchase orders have no screenshot yet. Sites, employees, customers, products, currency and the ledger are from the running app, on seed data.'
          ),
          decision(
            'Leave Live blank rather than a hash link',
            'The old page’s Live Project pointed at nothing. Recruiteware can say DigitalOcean because that URL exists. SesaHub will say it when there is a URL.'
          ),
        ],
        outcome: blocks(
          'This page describes the modules that run, and the one that does not, without filling gaps from the old Webflow CMS.'
        ),
      },
    ],
  },
  designToCode: {
    eyebrow: '05 / Design to code',
    heading: 'Where building protected the design',
    framing: blocks(
      'The information architecture is the tenant: company, then sites, people, parties, parts and books. Laravel, Inertia and React are how those records stay on one login. TypeScript pages under Enterprise and Core Financials are the screens. Docker on Render is how it shipped.'
    ),
    decisions: [
      decision(
        'Policies on the company, not a global admin flag',
        'RBAC and company policies are the isolation. A consultant’s cross-company role is still a role on a company, not a pass to every table.'
      ),
      decision(
        'Let services issue the codes',
        'Site codes and employee IDs come from the service layer so lists stay joinable when someone forgets a naming convention.'
      ),
      decision(
        'Keep conversion in the app',
        'Currency convert and update-rates are endpoints, not a spreadsheet beside the ERP.'
      ),
    ],
    stackTags: [
      'Laravel 11',
      'PHP',
      'React',
      'TypeScript',
      'Inertia.js',
      'Tailwind CSS',
      'PostgreSQL',
      'Docker',
      'Render',
    ],
  },
  outcomeStatus: {
    eyebrow: '06 / Outcome and status',
    heading: 'Where the product stood',
    statusSummary:
      'SesaHub shipped on Render as Nyande ERP Solutions, October 2025, after work that started in December 2024. The running app is seeded with test data. There is no external client and no named quote. The live URL is not on this page until there is one to give. Purchase-order request-to-receipt is not claimed as shipped.',
    whatsNext:
      'Finish the purchase-order workflow. Capture module screenshots from the running app. Add a live link if a shareable URL exists. The mobile app, voice and AI items on the older page are later work, not this release.',
    quotes: [],
    evidence: [
      'Deployed on Render with Docker, nginx, PHP-FPM and PostgreSQL.',
      'Company-scoped RBAC across companies, sites, employees, customers, suppliers, products, currencies and core financials.',
      'General ledger, chart of accounts, journal entries and fiscal calendar are in the running app. The screenshot is TechCorp test data. Purchase-order request-to-receipt is not.',
    ],
    reflection: blocks(
      'The honest version of this project is an internal ERP, built in order: tenant, then sites and people, then stock and currency, then the books. I would still start with isolation. I would not publish a purchase-order gallery I cannot show, and I would not describe MemberPress as this stack.'
    ),
  },
}
